language: python
python:
  - "3.7"

before_install:
  - head -c 32 /dev/random | base64 > etc/django-secret.key
  - pip install pylint pylint-django

install:
  - pip install -r requirements.txt

script:
  - make check

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
