language: python
python:
  - "3.7"

before_install:
  - pip install pylint pylint-django

install:
  - pip install -r requirements.txt

script:
  - pylint --load-plugins pylint_django -E fmrweb
  - python3 -Wall manage.py test -v 2 --failfast

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
