sudo: false

os:
  - linux

language: ruby

addons:
  sauce_connect: true

install:
  - bundle install

script:
  - bundle exec middleman build

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
